### PR TITLE
adding dropwizard-keycloak as a module

### PR DESCRIPTION
**Pull request by ahus1**
there is no publicly downloadable maven artefact yet, so I left the maven part empty. I will add it as soon as my module has been released.

### CODE REVIEW

**Comment by jplock** [comment]
Thanks!

**Comment by ahus1** [comment]
@jplock - I see that you have merged the PR, but I don't see a change online. Did you receive any notification from jekyll?

**Comment by jplock** [comment]
I haven't rebuilt the docs.  I'm currently traveling so I won't be able to do this right away.  /cc @dropwizard/committers

**Comment by arteam** [comment]
I've pushed the changes to the site branch. The module should be available now at http://modules.dropwizard.io/thirdparty/

**Pull request merged**
