### PR TITLE
Adding dependency injection with dropwizard-petite

### PR DESCRIPTION
**Pull request by mtakaki**
Adding `dropwizard-petite` bundle package, which adds Jodd Petite for light-weight dependency injection.

### CODE REVIEW

**Comment by joschi** [comment]
@mtakaki Thanks!

**Comment by nickbabcock** [comment]
Ah, is the name supposed to be `dropwizard-circuitbreaker`?

**Comment by mtakaki** [comment]
Oops, I copy-pasted it and forgot to change the first line! :(

**Comment by joschi** [comment]
@nickbabcock @mtakaki Yes, just realized the typo and fixed it.

**Pull request merged**
